deployment script added

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,20 +26,18 @@ jobs:
         # Read the storage account name from the parameters file
         account_name=$(jq -r '.parameters.storageAccountName.value' './parameters.json')
         echo "$account_name"
+        
         # Wait for a certain period to allow resource provisioning to complete
         sleep 30
         
-        # Query the provisioning state
-        provisioning_state=$(az storage account show --name $account_name --query "provisioningState" --output tsv)
+        # Query the storage account using --ids to check existence
+        az storage account show --ids "/subscriptions/112b128e-2295-43f5-aebe-b882b8d039d3/resourceGroups/demo-rg/providers/Microsoft.Storage/storageAccounts/$account_name" > /dev/null 2>&1
         
-        # Check the provisioningState and take action accordingly
-        if [ "$provisioning_state" = "Succeeded" ]; then
+        # Check the exit code and take action accordingly
+        if [ $? -eq 0 ]; then
           echo "Deployment succeeded"
         else
           echo "Deployment failed"
           exit 1
         fi
-       
-
-
-
+        
