first commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,12 +16,46 @@ env:
   AZURE_RESOURCEGROUP_NAME: demo-rg
 
 jobs:
+  check_manual_changes:
+    name: check_manual_changes
+    runs-on: ubuntu-latest
+
+     # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+
+      - name: Login to Azure
+        uses: azure/login@v1
+        with:
+            creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
+            
+      - name: Validate App Service Configuration
+        working-directory: '${{github.workspace}}/bicep'
+        id: validate_config
+        run: |
+          # Get the current state of the App Service
+          currentConfig=$(az webapp show --resource-group demo-rg --name webAppMNIT2-POC --query "{name: name, appSettings: appSettings}" -o json)
+          echo $currentConfig
+          # Compare current state with expected state in Bicep template
+          expectedConfig=$(cat webapp.bicep | grep -A 1 'Microsoft.Web/sites@' | grep -v 'Microsoft.Web/sites@')
+          
+          echo $expectedConfig
+
+          if [ "$currentConfig" != "$expectedConfig" ]; then
+            echo "Manual changes detected in App Service configuration. Aborting deployment."
+            exit 1
+          else
+            echo "No manual changes detected. Proceeding with deployment."
+          fi
+
  # This workflow contains a single job called "build"
   bicep_build:
     name: bicep build 
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
+    needs: [check_manual_changes]
+    
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -41,7 +75,6 @@ jobs:
         working-directory: '${{github.workspace}}/bicep'
         run: |
           az deployment group what-if --resource-group demo-rg --template-file './webapp.bicep' --parameters parameters.json
-
 
       - name: 'deploy webapp bicep'
         working-directory: '${{github.workspace}}/bicep'
