postdeplyment job implemented

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,9 +25,9 @@ jobs:
 
         echo "Printing storage account name: $STORAGE_ACCOUNT_NAME"
         az storage account show --name storageaccount15041995 --query "provisioningState" --output tsv
-        if [ "$(az storage account show --name storageaccount15041995 --query "provisioningState" --output tsv)" = "Succeeded" ]; then
-          echo "Deployment succeeded"
-        else
-          echo "Deployment failed"
-          exit 1
-        fi
+#        if [ "$(az storage account show --name storageaccount15041995 --query "provisioningState" --output tsv)" = "Succeeded" ]; then
+#          echo "Deployment succeeded"
+#        else
+#          echo "Deployment failed"
+#          exit 1
+#        fi
